### ISSUE TITLE
new issue arise.

### ISSUE THREAD

**Issue by Az0na** [Muletia/LUI#4]
44x LUI\unitframes\core\elements\pvp-PvP.lua:55: attempt to call global 'UnitPrestige' (a nil value)
LUI\unitframes\core\elements\pvp-PvP.lua:55: in function <LUI\unitframes\core\elements\pvp.lua:44>
(tail call): ?
LUI\unitframes\core\ouf.lua:163: in function <LUI\unitframes\core\ouf.lua:154>
(tail call): ?
LUI\unitframes\core\ouf.lua:163: in function `UpdateAllElements'
LUI\unitframes\layout\meta.lua:38: in function `FormatName'
LUI\unitframes\layout\layout.lua:1695: in function `Info'
LUI\unitframes\options\toggle.lua:865: in function `ApplySettings'
LUI\unitframes\options\toggle.lua:92: in function `?'
LUI\unitframes\options\toggle.lua:57: in function `ToggleUnit'
LUI\unitframes\init.lua:242: in function <LUI\unitframes\init.lua:241>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0-12.lua:571: in function `EnableAddon'
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:435: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:554: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1165: in function <FrameXML\UIParent.lua:1063>
[C]: ?

Locals:
nil

GL!

**Comment by Muletia** [comment]
First error should be fixed. Updated our PvP code with the latest oUF version. The second looks to be another addon.
