### ISSUE TITLE
Attempt to perform arithmetic on Boolean value...

### ISSUE THREAD

**Issue by Sethadon** [Muletia/LUI#7]
Message: ...face\AddOns\LUI\unitframes\core\elements\castbar.lua:265: attempt to perform arithmetic on local 'endTime' (a boolean value)
Time: Mon Jun 25 11:47:55 2018
Count: 1
Stack: ...face\AddOns\LUI\unitframes\core\elements\castbar.lua:265: attempt to perform arithmetic on local 'endTime' (a boolean value)
...face\AddOns\LUI\unitframes\core\elements\castbar.lua:265: in function <...face\AddOns\LUI\unitframes\core\elements\castbar.lua:256>
(tail call): ?

Locals: self = oUF_LUI_player {
 0 = <userdata>
 Highlight = <unnamed> {
 }
 PARTY_LOOT_METHOD_CHANGED = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\masterlooter.lua:73
 UNIT_MAXPOWER = <table> {
 }
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\castbar.lua:256
 SpellRange = true
 UNIT_MAXHEALTH = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\health.lua:145
 UNIT_POWER_FREQUENT = <table> {
 }
 UNIT_POWER_BAR_SHOW = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\power.lua:220
 UNIT_SPELLCAST_NOT_INTERRUPTIBLE = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\castbar.lua:204
 style = "LUI"
 RAID_TARGET_UPDATE = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\ricons.lua:58
 UNIT_CONNECTION = <table> {
 }
 BarFade = false
 unit = "player"
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\castbar.lua:218
 UNIT_SPELLCAST_STOP = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\castbar.lua:238
 XP = <unnamed> {
 }
 UPDATE_FACTION = <function> defined @Interface\AddOns\LUI\unitframes\plugins\oUF_Reputation.lua:48
 Rep = <unnamed> {
 }
 Experience = <unnamed> {
 }
 Overlay = <unnamed> {
 }
 __tags = <table> {
 }
 UNIT_ENTERED_VEHICLE = <table> {
 }
 Leader = <unnamed> {
 }
 UNIT_SPELLCAST_INTERRUPTIBLE = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\castbar.lua:190
 UNIT_HEALTH_FREQUENT = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\health.lua:145
 __unit = "player"
 Castbar = oUF_LUI_player_Castbar {
 }
 UNIT_DISPLAYPOWER = <table> {
 }
 UPDATE_EXHAUSTION = <function> defined @Interface\AddOns\LUI\unitframes\plugins\oUF_Experience.lua:92
 UNIT_PET_EXPERIENCE = <function> defined @Interface\AddOns\LUI\unitframes\plugins\oUF_Experience.lua:92
 _V2Tex = <unnamed> {
 }
 Health = <unnamed> {
 }
 UNIT_SPELLCAST_CHANNEL_STOP = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\castbar.lua:332
 UNIT_COMBAT = <function> defined @Interface\AddOns\LUI\unitframes\plugins\oUF_CombatFeedback.lua:62
 MasterLooter = <unnamed> {
 }
 SmoothBar = <function> defined @Interface\AddOns\LUI\unitframes\plugins\oUF_Smooth.lua:17
 PLAYER_ENTERING_WORLD = <table> {
 }
 PLAYER_ROLES_ASSIGNED = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\lfdrole.lua:57
 MoveableFrames = true
 Full = <unnamed> {
 }
 GROUP_ROSTER_UPDATE = <table> {
 }
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\castbar.lua:309
 PLAYER_FLAGS_CHANGED = <function> defined @Interface\AddOns\LUI\unitframes\layout\layout.lua:3250
 PARTY_LEADER_CHANGED = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\leader.lua:53
 __elements = <table> {
 }
 RaidIcon = <unnamed> {
 }
 UNIT_SPELLCAST_INTERRUPTED = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\castbar.lua:172
 Power = <unnamed> {
 }
 FrameBackdrop = <unnamed> {
 }
 Reputation = <unnamed> {
 }
 DruidMana = <unnamed> {
 }
 Assistant = <unnamed> {
 }
 UNIT_SPELLCAST_START = <function> defined @Interface\AddOns\LUI\unitframes\core\elements\castbar.lua:104
 PLAYER_LEVEL_UP = <function> defined @Interface\AddOns\LUI\unitframes\plugins\oUF_Experience.lua:92
 UNIT_FACTION = <table> {
 }
 PLAYER_XP_UPDATE = <function> defined @Interface\AddOns\LUI\unitframes\plugins\oUF_Experience.lua:92
 UNIT_EXITED_VEHICLE = <table> {
 }
 Info = <unnamed>

**Comment by Muletia** [comment]
Are you sure you're using the latest version? That one should have been fixed already.

What were you casting, or did you have somebody else targeted that was casting a channeled cast?

**Comment by Sethadon** [comment]
You're right, I had some left over files in there from a previous version. After a "clean" removal and install, the message is gone. Thanks for the quick response! 👍
